### ISSUE TITLE
Disconnected trying to upload art folder

### ISSUE THREAD

**Issue by Alexplose** [xchwarze/samsung-tv-ws-api#73]
Here is the error I get when uploading.
Randomly I get this error, after about 4 uploads, rarely more, and never got more than 10 uploads.

Any clue ?

```
INFO:root:[{'content_id': 'MY_F0143', 'category_id': 'MY-C0002', 'matte_id': 'shadowbox_polar', 'portrait_matte_id': 'flexible_polar', 'width': 2880, 'height': 2160, 'image_date': '2022:03:09 18:21:46', 'content_type': 'mobile'}, {'content_id': 'MY_F0142', 'category_id': 'MY-C0002', 'matte_id': 'shadowbox_polar', 'portrait_matte_id': 'flexible_polar', 'width': 2880, 'height': 2160, 'image_date': '2022:03:09 18:21:36', 'content_type': 'mobile'}]
INFO:root:{'data': '{\n  "id": "602bb01d-dcff-4e5a-8e49-7af585f69d87",\n  "event": "ready_to_use",\n  "conn_info": "{\\"contentInfo\\":\\"{\\\\\\"d2d_mode\\\\\\":\\\\\\"socket\\\\\\",\\\\\\"connection_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"request_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"id\\\\\\":\\\\\\"602bb01d-dcff-4e5a-8e49-7af585f69d87\\\\\\"}\\",\\"event\\":\\"get_d2d_connection\\",\\"ip\\":\\"192.168.1.190\\",\\"port\\":\\"52005\\",\\"key\\":\\"7r9e2ozo\\",\\"stat\\":\\"ok\\",\\"mode\\":\\"socket\\"}"\n}', 'event': 'd2d_service_message', 'from': '31d8a1d4-339b-4a62-a3e8-cf30e4a37387'}
INFO:root:{'data': {'attributes': {'name': 'U2Ftc3VuZ1R2UmVtb3Rl'}, 'connectTime': 1646846647436, 'deviceName': 'U2Ftc3VuZ1R2UmVtb3Rl', 'id': '8281ee4c-71e-44d8-a63a-adc5aa442274', 'isHost': False}, 'event': 'ms.channel.clientDisconnect'}
Traceback (most recent call last):
  File "/share/the_frame/art.py", line 66, in <module>
    tv.art().upload(data, file_type='JPEG')
  File "/usr/lib/python3.9/site-packages/samsungtvws/art.py", line 211, in upload
    data = json.loads(response["data"])
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

```

**Comment by epenet** [comment]
This happens because currently the art class doesn't currently handle extra messages that may be inserted by the TV.

#74 should fix that

**Comment by Alexplose** [comment]
I'm still having errors 

`Traceback (most recent call last):
  File "/share/the_frame/art.py", line 80, in <module>
    tv.art().upload(data, file_type='JPEG')
  File "/usr/lib/python3.9/site-packages/samsungtvws/art.py", line 244, in upload
    data = json.loads(response["data"])
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
`

**Comment by epenet** [comment]
You do not seem to be using the latest code base (the line numbers don't match).

**Comment by Alexplose** [comment]
> You do not seem to be using the latest code base (the line numbers don't match). Did you try it with the latest master, since #74 was merged?

I'm up to date with master, https://github.com/xchwarze/samsung-tv-ws-api/blob/f92648cddc10f1263cb96281944b0c2c3978826a/samsungtvws/art.py#L244

Is says line 245 because I added a logging on line 244 to show the response.

**Comment by epenet** [comment]
Does it work if you replace lines 242-244?
https://github.com/xchwarze/samsung-tv-ws-api/blob/f92648cddc10f1263cb96281944b0c2c3978826a/samsungtvws/art.py#L242-L244

With this:
```python
        assert self.connection
        event: Optional[str] = None
        while event != D2D_SERVICE_MESSAGE_EVENT:
            data = self.connection.recv()
            response = helper.process_api_response(data)
            event = response.get("event", "*")
            assert event
            self._websocket_event(event, response)
        data = json.loads(response["data"])
```

**Comment by epenet** [comment]
It is the same content as #74, but in a different location...

**Comment by epenet** [comment]
Do you want to do the honours with the PR?

**Comment by Alexplose** [comment]
This is your fix, I didn't contribute, only reporting issues, do the PR.

The upload is hanging sometimes, have to interrupt and relaunch.

```
Traceback (most recent call last):
  File "/share/the_frame/art.py", line 85, in <module>
    tv.art().upload(data, file_type='JPEG')
  File "/usr/lib/python3.9/site-packages/samsungtvws/art.py", line 251, in upload
    data = self.connection.recv()
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 362, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 385, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python3.9/site-packages/websocket/_abnf.py", line 341, in recv_frame
    self.recv_header()
  File "/usr/lib/python3.9/site-packages/websocket/_abnf.py", line 297, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python3.9/site-packages/websocket/_abnf.py", line 376, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python3.9/site-packages/websocket/_socket.py", line 111, in recv
    bytes_ = _recv()
  File "/usr/lib/python3.9/site-packages/websocket/_socket.py", line 90, in _recv
    return sock.recv(bufsize)
KeyboardInterrupt


```

**Comment by Alexplose** [comment]
Sometime I receive the wrong response from upload, last message doesn't contains conn_info, but event of image_added.


```
INFO:root:{'data': '{\n  "id": "6bf469e8-e822-4451-9e32-bb994a18c0d7",\n  "event": "ready_to_use",\n  "conn_info": "{\\"contentInfo\\":\\"{\\\\\\"d2d_mode\\\\\\":\\\\\\"socket\\\\\\",\\\\\\"connection_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"request_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"id\\\\\\":\\\\\\"6bf469e8-e822-4451-9e32-bb994a18c0d7\\\\\\"}\\",\\"event\\":\\"get_d2d_connection\\",\\"ip\\":\\"192.168.1.190\\",\\"port\\":\\"51912\\",\\"key\\":\\"xl1ubp1v\\",\\"stat\\":\\"ok\\",\\"mode\\":\\"socket\\"}"\n}', 'event': 'd2d_service_message', 'from': '1722771-eb20-41a0-a233-1decdd65dd9d'}


INFO:root:{'data': '{\n  "event": "image_added",\n  "content_id": "MY_F0424",\n  "category_id": "MY-C0002",\n  "matte_id": "shadowbox_polar",\n  "portrait_matte_id": "flexible_polar",\n  "width": "2880",\n  "height": "2160"\n}', 'event': 'd2d_service_message', 'from': '1722771-eb20-41a0-a233-1decdd65dd9d'}
Traceback (most recent call last):
  File "/share/the_frame/art.py", line 87, in <module>
    tv.art().upload(data, file_type='JPEG')
  File "/usr/lib/python3.9/site-packages/samsungtvws/art.py", line 225, in upload
    conn_info = json.loads(data["conn_info"])
KeyError: 'conn_info'

```

**Comment by epenet** [comment]
I guess you may need to adjust `_send_art_request` a little more, so that you check `event` AND `sub-event`.
For example:
```python
    def _send_art_request(
        self,
        request_data: Dict[str, Any],
        wait_for_event: Optional[str] = None,
        wait_for_sub_event: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        request_data["id"] = self.art_uuid
        self.send_command(ArtChannelEmitCommand.art_app_request(request_data))

        if not wait_for_event:
            return None

        assert self.connection
        event: Optional[str] = None
        sub_event: Optional[str] = None
        while event != wait_for_event:
            data = self.connection.recv()
            response = helper.process_api_response(data)
            event = response.get("event", "*")
            assert event
            self._websocket_event(event, response)
            if event == wait_for_event and wait_for_sub_event:
                # Check sub event, reset event if it doesn't match
                data = json.loads(response["data"])
                sub_event = data.get("event", "*")
                if sub_event != wait_for_sub_event:
                    event = None

        return response
```

Since I do not use upload myself, I would prefer that you test and create the PR... I am only giving indications
